# Generated by Django 5.0 on 2024-09-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.productcategory",
                verbose_name="Категория товара",
            ),
        ),
        migrations.AddField(
            model_name="subcity",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcities",
                to="orders.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="from_subcity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_from_subcity",
                to="orders.subcity",
                verbose_name="Подгород откуда",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="to_subcity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_to_subcity",
                to="orders.subcity",
                verbose_name="Подгород куда",
            ),
        ),
    ]
