# Generated by Django 5.0 on 2024-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Обработка заказа"),
                    ("dispatched", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("canceled", "Отменен"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
