# Generated by Django 5.0 on 2024-09-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
        ('ransom', '0004_remove_purchaseorder_from_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_label',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товара'},
        ),
        migrations.AlterModelOptions(
            name='subcity',
            options={'verbose_name': 'Подгород', 'verbose_name_plural': 'Подгорода'},
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Примерное время прибытия'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_processing', 'Обработка заказа'), ('assigning_courier', 'Назначаем курьера'), ('courier_on_way', 'Курьер в пути'), ('order_shipped', 'Отгрузка заказа'), ('order_received', 'Заказ получен')], default='order_processing', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='ID заказа'),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
