# Generated by Django 5.0 on 2024-10-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя получателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Телефон получателя'),
            preserve_default=False,
        ),
    ]
