# Generated by Django 5.0 on 2024-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_receiver_name_order_receiver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='price_category',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
