# Generated by Django 5.0 on 2024-09-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_order_id'),
        ('ransom', '0002_purchaseorder_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Обработка заказа'), ('courier_assigned', 'Назначаем курьера'), ('on_the_way', 'Курьер в пути'), ('shipped', 'Отгрузка заказа'), ('delivered', 'Заказ получен')], default='processing', max_length=20, verbose_name='Статус заказа')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='Примерная дата прибытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='my_orders_o_order_i_07c24b_idx'), models.Index(fields=['status'], name='my_orders_o_status_da8130_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Обработка заказа'), ('courier_assigned', 'Назначаем курьера'), ('on_the_way', 'Курьер в пути'), ('shipped', 'Отгрузка заказа'), ('delivered', 'Заказ получен')], default='processing', max_length=20, verbose_name='Статус выкупа')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='Примерная дата прибытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ransom.purchaseorder', verbose_name='Выкуп')),
            ],
            options={
                'verbose_name': 'Статус выкупа',
                'verbose_name_plural': 'Статусы выкупов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase_order'], name='my_orders_p_purchas_0fb2ca_idx'), models.Index(fields=['status'], name='my_orders_p_status_fff992_idx')],
            },
        ),
    ]
