# Generated by Django 5.0 on 2024-09-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderstatus',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderStatus',
        ),
    ]
