# Generated by Django 5.0 on 2024-10-13 08:39

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('privacy_policy', models.URLField(blank=True, null=True, verbose_name='Политика конфиденциальности')),
                ('data_processing_policy', models.URLField(blank=True, null=True, verbose_name='Политика обработки данных')),
            ],
            options={
                'verbose_name': 'О приложении',
                'verbose_name_plural': 'О приложении',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to=apps.utils.custom_upload_path, verbose_name='Изображение')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('sub_title', models.CharField(max_length=100, null=True, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to=apps.utils.custom_upload_path, verbose_name='Изображение')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество посещений')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Вопросы и ответы',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона для поддержки')),
                ('ad_phone_number', models.CharField(max_length=20, verbose_name='Номер телефона для рекламы')),
            ],
            options={
                'verbose_name': 'Поддержка',
                'verbose_name_plural': 'Поддержка',
            },
        ),
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(max_length=255, verbose_name='Версия приложения')),
                ('android_force_update', models.BooleanField(default=False, verbose_name='Принудительное обновление')),
                ('ios_version', models.CharField(max_length=255, verbose_name='Версия приложения')),
                ('ios_force_update', models.BooleanField(default=False, verbose_name='Принудительное обновление')),
            ],
            options={
                'verbose_name': 'Управление версией приложения',
            },
        ),
    ]
