# Generated by Django 5.0 on 2024-10-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_offeragreement_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeragreement',
            options={'verbose_name': 'ДОГОВОР ОФЕРТЫ', 'verbose_name_plural': 'ДОГОВОР ОФЕРТЫ'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ', 'verbose_name_plural': 'ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ'},
        ),
    ]
