# Generated by Django 5.0 on 2024-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_id',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True, verbose_name='ID заказа'),
            preserve_default=False,
        ),
    ]
