# Generated by Django 5.0 on 2024-09-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
        ('ransom', '0002_purchaseorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='from_subcity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders_from_subcity', to='orders.subcity', verbose_name='Подгород откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='to_subcity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders_to_subcity', to='orders.subcity', verbose_name='Подгород куда'),
            preserve_default=False,
        ),
    ]
