# Generated by Django 5.0 on 2024-10-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_receiver_name_order_receiver_phone'),
        ('ransom', '0003_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='article',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product_url',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='from_subcity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders_from_subcity', to='orders.subcity', verbose_name='Подгород откуда'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='to_subcity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders_to_subcity', to='orders.subcity', verbose_name='Подгород куда'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_url', models.URLField(verbose_name='Ссылка на товар')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='orders.productcategory', verbose_name='Категория товара')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ransom.purchaseorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
    ]
