# Generated by Django 5.0 on 2024-09-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0003_purchaseorder_from_subcity_purchaseorder_to_subcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='from_label',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Примерное время прибытия'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('order_processing', 'Обработка заказа'), ('assigning_courier', 'Назначаем курьера'), ('courier_on_way', 'Курьер в пути'), ('order_shipped', 'Отгрузка заказа'), ('order_received', 'Заказ получен')], default='order_processing', max_length=20, verbose_name='Статус'),
        ),
    ]
