# Generated by Django 5.0 on 2024-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0004_remove_purchaseorder_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='keep_shoe_box',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='pickup_service',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='keep_shoe_box',
            field=models.BooleanField(default=False, verbose_name='Сохранить коробку из под обуви'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='pickup_service',
            field=models.BooleanField(default=False, verbose_name='Услуга вылова товара'),
        ),
    ]
